### ISSUE TITLE
Add Scope rules for hierarchy of org > campaign > project

### ISSUE THREAD

**Issue by dotsdl** [openforcefield/fah-alchemy#42]
Currently, `Scope` is just a triple of strings representing `org`, `campaign`, `project`, with no sense of hierarchy between these levels. This results in cumbersome access permissions for e.g. a user that should have access to an `org` called `openff`: they will require an explicit entry for each `campaign` and `project` represented in that `org` to have full access, with new entries added as new `campaign`s and `project`s are created.

To avoid this, we'd like for the hierarchy between these levels to be made explicit, and for glob-based wildcards to be allowed. So, we could have e.g. `*-*-*` (all scopes), `openff-*-*` (all `org` 'openff' scopes), `openff-rosemary-*` (all `org` 'openff', `campaign` 'rosemary' scopes), as allowed entries in a user's list of `Scope`s.

This hierarchy enforcement should disallow entries like `*-rosemary-*` (access to any `campaign` called 'rosemary', anywhere). In other words, one cannot limit scope at a level lower when given broadest scope at a level higher.

Ideally, `Scope` validity is enforced in the [Pydantic model itself](https://github.com/openforcefield/fah-alchemy/blob/0cdfa891cddbc55cf8d6daaaded719903dc89ad4/fah_alchemy/models.py#L6-L16) on creation.

**Comment by dotsdl** [comment]
@hmacdope is this one of interest to you? It's the next step in completing the vision laid out in #33. To that end, after this #43 would become tractable.

**Comment by hmacdope** [comment]
Absolutely :)

**Comment by hmacdope** [comment]
Question, does `ScopedKey` also need the same validation?

**Comment by dotsdl** [comment]
> Question, does `ScopedKey` also need the same validation?

`ScopedKey` doesn't, because a `ScopedKey` should refer to a real object, which will always have a "specific" scope (a scope with no wildcards).
