### ISSUE TITLE
Add an underscore method to `FahAlchemyClient` and `FahAlchemyComputeClient` that checks connectivity of API to storage components

### ISSUE THREAD

**Issue by dotsdl** [openforcefield/fah-alchemy#55]
We would like a `_api_check` method added to the `FahAlchemyBaseClient` that hits a `/check` endpoint on its target API. The `/check` endpoint on each of `FahAlchemyAPI` and `FahAlchemyComputeAPI` should be implemented to hit both the state store (Neo4j) and the object store (S3) in such a way that it simply checks that these services are meaningfully reachable. 

The `/check` endpoint should return a `200 OK` HTTP status if the services are reachable, and an appropriate status code if they are not. The `_api_check` method on each client should raise an exception if any status code other than `200 OK` comes back.

These methods would be used for checking that a deployment via e.g. `docker-compose` is up and working as expected.

**Comment by dotsdl** [comment]
@hmacdope this is a good first issue, as it touches many of the components of the `fah-alchemy` architecture, but doesn't require *too much* domain detail on what these components do. You will likely be able to draw on the existing patterns in each component to implement what's needed for each. 

I'm happy to clarify/assist at any point you need!

**Comment by hmacdope** [comment]
Roger that 👍
