### ISSUE TITLE
Add CLI point for adding user / compute identities

### ISSUE THREAD

**Issue by dotsdl** [openforcefield/fah-alchemy#63]
We need to be able to add user and compute identities via the command-line interface on the hosting resource. This will require credentials for the state store, and should take as input the identity type (user, compute), identifier, and key.

**Comment by dotsdl** [comment]
@hmacdope are you interested in taking this one on? If not, I can tackle it.

**Comment by hmacdope** [comment]
@dotsdl yeah for sure I'll have a crack
